# docker-compose.yml
version: '3.8'
services:
  # メインの開発環境サービス
  main_workspace:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspaces:cached
    environment:
      - COMPOSE_PROJECT_NAME=simple_contract_management-system
    command: sleep infinity 
   